scrape_configs:
  - job_name: dev
    static_configs:
      - targets: [kepler-dev:8888]

  - job_name: scaphandre
    static_configs:
      - targets: [scaphandre:8080]
    scheme: http
    fallback_scrape_protocol: PrometheusText1.0.0

  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]

  - job_name: libvirt-exporter
    static_configs:
      - targets: [libvirt-exporter:9177]

  - job_name: process-exporter
    static_configs:
      - targets: [process-exporter:9256]
