scrape_configs:
  - job_name: dev
    static_configs:
      - targets: [kepler-dev:8888]

  - job_name: scaphandre
    static_configs:
      - targets: [scaphandre:8080]

  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]
