name: base

on:
  workflow_dispatch:
    inputs:
      pushImage:
        default: true
        type: boolean

jobs:
  baseimagebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay
        if: ${{ inputs.pushImage }}
        uses: docker/login-action@v3
        with:
            registry: quay.io/sustainable_computing_io
            username: ${{ secrets.BOT_NAME }}
            password: ${{ secrets.BOT_TOKEN }}
      - name: Build and push a base image for building Kepler with libbpf
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile.builder
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: ${{ inputs.pushImage }}
          tags: quay.io/sustainable_computing_io/kepler_builder:ubi-9-libbpf-1.2.0
